### ISSUE TITLE
Upload Server step fails

### ISSUE THREAD

**Issue by MarcusDenker** [pharo-project/pharo-site#10]
After merging, we get an error in the build:

https://github.com/pharo-project/pharo-site/actions/runs/3638625686/jobs/6141039919

```
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
[19](https://github.com/pharo-project/pharo-site/actions/runs/3638625686/jobs/6141039919#step:6:20)
rsync error: unexplained error (code 255) at io.c(228) [sender=3.2.3]
```

**Comment by fmqa** [comment]
Any plans to fix this? The last successful push job is almost a month old, and there were many changes since then. It's fairly evident that the website is outdated now.

**Comment by MarcusDenker** [comment]
Yes, we are working on fixing this

**Comment by MarcusDenker** [comment]
Fixed!
