### ISSUE TITLE
Cleanup https://pharo.org/blogs

### ISSUE THREAD

**Issue by privat** [pharo-project/pharo-site#12]
Cleanup (or remove) https://pharo.org/blogs as there are unmaintained blogs or broken links.
I found the page through a search engine.

I'm not sure how the information is redundant with https://pharo.org/community

**Comment by MarcusDenker** [comment]
Yes, I think we should remove it for now

If we list community blogs, this has to be done in a way that old entries are cleaned up automatically

Else this will be always full of out of date links

**Comment by astares** [comment]
Yes - blogging is not modern anymore these days. This gives the wrong impression as if community is not active.
Also community members changed so many blogs stopped on the topic.

Personally I also find it easier to tweet / share news via retweet than updating/maintaining the blog. Time is always an issue.

But we should preserve the list - maybe it could be moved to the https://github.com/pharo-open-documentation/pharo-wiki

**Comment by jordanmontt** [comment]
Yes, but I think that we should link the Pharo dev (https://thepharo.dev/) as it is maintained by us and we post content from time to time

**Comment by MarcusDenker** [comment]
But this is linked from https://www.pharo.org/community

**Comment by jordanmontt** [comment]
Ah yes, sorry I missed that
